- hosts: all
  become: yes
  roles:
    - dokku_bot.ansible_dokku
  vars:
    dokku_version: 0.21.4
    dokku_vhost_enable: true
    dokku_skip_key_file: true
    dokku_hostname: lebedev.lt
    dokku_plugins:
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
